[package]
name = "pc/heliosredux"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
vide = "centau/vide@0.2.0"
cmdr = "evaera/cmdr@1.12.0"
promise = "evaera/promise@4.0.0"
janitor = "howmanysmall/janitor@1.17.0"
knit = "sleitnick/knit@1.7.0"